### ISSUE TITLE
panic: Reuse of exported var name: eth

### ISSUE THREAD

**Issue by StupidTAO** [jdcloud-bds/bds#1]
(NOTE: Please use this template while reporting a bug and provide as much info as possible)

**Bug description**
when add JustitiaSplitter to bsd/splitter/spliter.go file, compilation can be passed, running will generate an painc error:  Reuse of exported var name: eth

**Expected behavior**
Justitia splitter code runs normally and can parse block information

**Steps to reproduce the bug**
Create a new chain of splitters,  added to the bds/splitter/splitter.go file Run() function,start and run .

**Environment**:go
* Version:1.11.1
* Cloud provider or hardware configuration:
* OS :Mojave 10.14.5 
* Others:

``

configfile: 
#占用cup核心数
[global]
max_process = 1

#堆栈监控
[profiling]
enable = true
host = 0.0.0.0
port = 6062

#内部数据监控
[metric]
enable = false
host = 0.0.0.0
port = 6063
path = /metrics

# =============================== justitia ==================================
[justitia]
#是否开启 justitia 数据splitter
enable = true
#是否开启数据库
database_enable = true
#数据库worker缓存大小
database_worker_buffer = 8192
#数据库worker数量
database_worker_number = 1
#一次请求区块链数据的最大块数,400000块之前可以设置大一些，比如300
max_batch_block = 30
#justitia 全节点的地址
endpoint = http://127.0.0.1:47768
#运行 justitia 全节点设置的用户名
user = 0xc3b5e92111484503b98c0283206ff2f4239fb06b
#运行 justitia 全节点设置的密码
password = 123
#justitia 数据校验规则文件地址
json_schema_file = /etc/bds-splitter/schema/justitia.json↩
#justitia 数据校验是否开启
json_schema_validation_enable = false

#justitia 定时任务配置
[cron.justitia]
update_meta_expr = @every 1m

#justitia kafka 配置
[kafka.justitia]
enable = true
#topic = justitia
topic = justitia
# kafka 客户端标示
client_id = justitia-client-1
# kafka 消费组标示
group_id = justitia-group
# kafka 服务的地址
broker_list = localhost:9092
buffer_size = 1000
return_errors = true

#justitia 数据库配置
[database.justitia]
#数据库类型，sql server为mssql，postgre为postgres
type = postgres
#数据库的访问地址
host = 127.0.0.1
#数据库的端口信息
port = 5432
#数据库的库名，需要初始化好，创建表和导入数据用
database = justitia
#数据库的访问账号
user = postgres
#数据库的访问账号密码信息
password = 123
timezone = Asia/Shanghai
max_open_conns = 500
max_idle_conns = 100
sql_log_file = /var/log/bds-splitter/justitia-sql.log
debug = false

max_idle_conns = 100
sql_log_file = /var/log/bds-splitter/justitia-sql.log
debug = false

# =============================== log ==================================
#普通日志配置
[logging_normal]
writers = console,file
log_file = /var/log/bds-splitter/normal.log
log_level = debug
caller_level_skip = 5
format = short
max_size = 100m
daily = true

#错误日志配置
[logging_detail]
writers = console,file
log_file = /var/log/bds-splitter/detail.log
log_level = debug
caller_level_skip = 5
format = long
max_size = 100m
daily = true

**Comment by SalleryWang** [comment]
Maybe you mix up  with the eth pakage.check it.
