### ISSUE TITLE
splitter无法读取kafka数据的疑问

### ISSUE THREAD

**Issue by chenshubiao** [jdcloud-bds/bds#5]
您好，我刚开始学习区块链这方面的知识。按照您提供的文档我已经搭建了一套环境，比特币节点启动，kafka也受到了消息。启动splitter后，数据库中也自动生成了相关表项。但是没有数据，这是我很疑惑，希望您给予指点！谢谢！
××××××××××××××××××××××KafkaRESTProxy里的信息只有POST，没GET××××××××××××
[2020-03-22 21:05:20,259] INFO 192.168.31.94 - - [22/三月/2020:13:05:20 +0000] "POST /topics/btc HTTP/1.0" 200 120  2 (io.confluent.rest-utils.requests:62)

××××××××××××××××××××splitter的错误日志一直报这个错××××××××××××××××××××
2020-03-22 21:02:43.436 ERROR [github.com/jdcloud-bds/bds/splitter/btc.(*BTCSplitter).CheckBlock:117] - Post http://192.168.31.94:8333:8332: invalid URL port "8333:8332"

×××××××××××××××××××信息日志里报如下的warning××××××××××××××××××××××××
2020-03-22 21:02:43.384 DEBUG - splitter btc: checking block 101105
2020-03-22 21:02:43.385 WARN  - splitter btc: can not find previous block 101104
2020-03-22 21:02:43.385 DEBUG - splitter btc: get latest block -1 from database

××××××××××××××××××××××××××这是我splitter.conf的比特币相关部分×××××××××××××
# =============================== btc ==================================
[btc]
#是否开启 btc 数据splitter
enable = true
#是否开启数据库
database_enable = true
#数据库worker缓存大小
database_worker_buffer = 8192
#数据库worker数量
database_worker_number = 1
#一次请求区块链数据的最大块数,400000块之前可以设置大一些，比如300
max_batch_block = 300
#btc全节点的地址 
endpoint = http://192.168.31.94:8333:8332
#运行 btc 全节点设置的用户名
#user = [rpc 访问账号]
#运行 btc 全节点设置的密码
#password = [rpc 访问密码]
#btc数据校验规则文件地址
json_schema_file = /etc/bds-splitter/schema/btc.json↩
#btc数据校验是否开启
json_schema_validation_enable = false

#btc定时任务配置
[cron.btc]
update_meta_expr = @every 1m

#btc kafka 配置
[kafka.btc]
enable = true
topic = btc
# kafka 客户端标示
client_id = btc-client-1
# kafka 消费组标示
group_id = btc-group
# kafka 服务的地址
broker_list = 192.168.31.94:9092
buffer_size = 1000
return_errors = true

务必烦请您百忙之中答疑解惑。这对我真的很重要！！万分感谢！！！！

**Comment by SalleryWang** [comment]
endpoint 写的有问题，看一下比特币全节点暴露的rpc端口

**Comment by chenshubiao** [comment]
> endpoint 写的有问题，看一下比特币全节点暴露的rpc端口
老师您好，我配置都是默认的，我查了一下bitcoind运行的地端口是8333，

**Comment by chenshubiao** [comment]
> endpoint 写的有问题，看一下比特币全节点暴露的rpc端口
感谢老师指导！！！问题已解决。给遇到同样问题的朋友一个解释
splitter.conf中的endpoint不是bitcoind的运行地址和端口，而是rpc的端口，地址设置为本机的IP，可以在bitcoin.conf中设置，我的rpcport设置为了18322.没有bitcoin.conf的可以在网上下载或拷贝。然后在运行.bitcoind的时候加 -conf=[你存放conf的绝对路径]，这样就可以了！！
