### ISSUE TITLE
无法消费数据

### ISSUE THREAD

**Issue by chenshubiao** [jdcloud-bds/bds#6]
(NOTE: Please use this template while reporting a bug and provide as much info as possible)

**Bug description**
splitter conf 中配置btc全节点运行地址，若为*.*.*.*:8333则会报错，若为kafka rest proxy的端口，则不报错，但kafka rest中报错。
ERROR Unhandled exception (io.confluent.rest.exceptions.KafkaExceptionMapper:123)
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token

**Expected behavior**
数据库仅生成表，没有数据插入
**Steps to reproduce the bug**
数据写入kafka正常，开启splitter无效，找不到区块block
**Environment**:
* Version:
* Cloud provider or hardware configuration:
* OS (e.g: `cat /etc/os-release`):
* Others:

**Comment by SalleryWang** [comment]
配置文件中[kafka.btc] 消费端口是否配置正确
