### ISSUE TITLE
eth->transaction 表中的 ‘V’ 字段 ‘char(2)’ 不够

### ISSUE THREAD

**Issue by nyfooo9** [jdcloud-bds/bds#7]
(NOTE: Please use this template while reporting a bug and provide as much info as possible)

**Bug description**
启动eth私链测试时，‘V‘ 的长度为3，导致 eth transaction 写入失败
**Expected behavior**

**Steps to reproduce the bug**

**Environment**: eth私链
* Version:当前最新bds测试
* Cloud provider or hardware configuration:
* OS (e.g: `cat /etc/os-release`):
* Others:

**Comment by SalleryWang** [comment]
我们对接的是公链数据，私链目前不考虑哈，thx
