### ISSUE TITLE
消费数据解析太慢的问题

### ISSUE THREAD

**Issue by chan1211** [jdcloud-bds/bds#8]
我是消费btc的数据，一开始应该是因为交易少，所以数据处理非常快。
消息保留时间是168个小时，现在消费到了140000个块，24小时勉强消费10000个block，这样的速度太慢了，不知有什么方法可以解析快一些。
期待您的回复。

**Comment by SalleryWang** [comment]
全节点同步慢？还是解析写入到数据库慢？

**Comment by nyfooo9** [comment]
写入数据库慢~
和机器配置也有关系，我们是16g i3的机器；开始比较快，后面越来越慢，半个多月才到20w块；
后来用bds源码 改为用hbase存储；三台hbase集群环境，btc测试链数据三四天就能跟上；btc正式链8小时存到20w块，集群机器比较差，正式链还没有同步完过。

**Comment by chenshubiao** [comment]
> 全节点同步慢？还是解析写入到数据库慢？
解析写入数据库慢。不过，看上面评论，看来是暂时没有什么办法了吧？

**Comment by SalleryWang** [comment]
你们什么需求呀？ 需要快速落到数据库，然后呢？

**Comment by SalleryWang** [comment]
可以并发写入

**Comment by chan1211** [comment]
> 可以并发写入

单机环境可行吗？（我试着再运行一个splitter，但它并没有处理数据）

**Comment by chan1211** [comment]
> 可以并发写入
老师，我真的好无奈啊。。。同时打开两个splitter的话，双方不知道对方的存在，同时处理一个区块，一个首先完成，另一个就报重复的错。
想着在创建一个topic，来解决这个问题。
但是运行bitcoind的时候出现了以下错误：
`************************
EXCEPTION: NSt8ios_base7failureB5cxx11E       
CAutoFile::write: write failed: iostream error       
bitcoin in ProcessMessages()       
`
出现多次相同错误后，我的移动硬盘（电脑磁盘不够，外接了移动硬盘）断连了，然后bitcoin因为打不开存储空间而放弃进程退出了。
莫名其妙的错误，之前一直都是好的，难道我的移动硬盘有问题了吗？
盼望老师答疑

**Comment by SalleryWang** [comment]
你可以并发消费写入 不是开两个splitter，你们是学生吗

**Comment by chan1211** [comment]
> 你可以并发消费写入 不是开两个splitter，你们是学生吗

现在24小时可能只能完成200块的数据了。这是数据库的问题吗？这样可能真的很难达到预期，有些遗憾了

**Comment by SalleryWang** [comment]
我们单线程也没这么慢啊！是不是你们全节点同步数据过慢




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

在2020年04月11日 18:43，chan1211 写道：

你可以并发消费写入 不是开两个splitter，你们是学生吗

现在24小时可能只能完成200块的数据了。这是数据库的问题吗？这样可能真的很难达到预期，有些遗憾了

**Comment by chan1211** [comment]
> 我们单线程也没这么慢啊！是不是你们全节点同步数据过慢 | | ThanosWei 邮箱：ThanosWei@163.com | 签名由 网易邮箱大师 定制 在2020年04月11日 18:43，chan1211 写道： 你可以并发消费写入 不是开两个splitter，你们是学生吗 现在24小时可能只能完成200块的数据了。这是数据库的问题吗？这样可能真的很难达到预期，有些遗憾了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

全节点早就同步到35万多高度了，这也太无奈了。有时候仅仅处理了2个交易的区块，也会进入长久的等待。我得想点其他办法了，这个恐怕是不行了
